/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    'cms-users': CmsUserAuthOperations;
  };
  blocks: {};
  collections: {
    'cms-users': CmsUser;
    'app-users': AppUser;
    'agency-profiles': AgencyProfile;
    'influencer-profiles': InfluencerProfile;
    'onboarding-settings': OnboardingSetting;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'app-users': {
      influencerProfile: 'influencer-profiles';
    };
  };
  collectionsSelect: {
    'cms-users': CmsUsersSelect<false> | CmsUsersSelect<true>;
    'app-users': AppUsersSelect<false> | AppUsersSelect<true>;
    'agency-profiles': AgencyProfilesSelect<false> | AgencyProfilesSelect<true>;
    'influencer-profiles': InfluencerProfilesSelect<false> | InfluencerProfilesSelect<true>;
    'onboarding-settings': OnboardingSettingsSelect<false> | OnboardingSettingsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: CmsUser;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface CmsUserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cms-users".
 */
export interface CmsUser {
  id: string;
  name: string;
  role: 'super_admin' | 'admin';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'cms-users';
}
/**
 * Users who sign in with mobile OTP. Mobile number is the main identifier.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app-users".
 */
export interface AppUser {
  id: string;
  /**
   * Login mobile number (e.g. +919876543210)
   */
  mobile: string;
  role: 'agency' | 'influencer' | 'brand';
  isMobileVerified?: boolean | null;
  lastOtpRequestedAt?: string | null;
  lastLoginAt?: string | null;
  influencerProfile?: {
    docs?: (string | InfluencerProfile)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Complete influencer profile — all 4 onboarding screens in one schema.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "influencer-profiles".
 */
export interface InfluencerProfile {
  id: string;
  name?: string | null;
  city?: ('Mumbai' | 'Delhi' | 'Bengaluru' | 'Hyderabad' | 'Chennai' | 'Kolkata') | null;
  userId?: (string | null) | AppUser;
  mobile: string;
  platforms?:
    | {
        platform: 'instagram' | 'youtube' | 'tiktok' | 'twitter' | 'facebook' | 'linkedin' | 'snapchat';
        username?: string | null;
        channelName?: string | null;
        followers?: number | null;
        subscribers?: number | null;
        engagement: number;
        id?: string | null;
      }[]
    | null;
  contentCategories?:
    | (
        | 'Fashion'
        | 'Lifestyle'
        | 'Beauty'
        | 'Fitness'
        | 'Food'
        | 'Travel'
        | 'Tech'
        | 'Finance'
        | 'Gaming'
        | 'Parenting'
        | 'Education'
        | 'Comedy'
        | 'Music'
        | 'Dance'
        | 'Photography'
        | 'Art & Design'
        | 'Health & Wellness'
        | 'Automobile'
        | 'Real Estate'
        | 'Sports'
        | 'Pets'
        | 'Spirituality'
        | 'News & Commentary'
        | 'DIY & Crafts'
      )[]
    | null;
  contentLanguages?:
    | (
        | 'Hindi'
        | 'English'
        | 'Tamil'
        | 'Telugu'
        | 'Bengali'
        | 'Marathi'
        | 'Gujarati'
        | 'Kannada'
        | 'Malayalam'
        | 'Punjabi'
        | 'Urdu'
        | 'Odia'
      )[]
    | null;
  bio?: string | null;
  collaborationPreference?: ('paid_only' | 'barter_product' | 'paid_and_barter') | null;
  rateRange?: {
    min?: number | null;
    max?: number | null;
    currency?: string | null;
  };
  pastCollaborations?: string[] | null;
  portfolioLink?: string | null;
  isProfileComplete?: boolean | null;
  completedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agency-profiles".
 */
export interface AgencyProfile {
  id: string;
  userId?: (string | null) | AppUser;
  mobile: string;
  agencyName?: string | null;
  contactPerson?: string | null;
  city?: string | null;
  agencyType?:
    | (
        | 'Talent Management'
        | 'Influencer Marketing'
        | 'Creative / Production'
        | 'PR & Communications'
        | 'Full-service Agency'
        | 'Boutique Agency'
      )
    | null;
  teamSize?: ('Solo' | '2-5' | '6-15' | '16-50' | '50+') | null;
  creatorsManaged?: ('1-10' | '11-25' | '26-50' | '51-100' | '100+') | null;
  focusAreas?:
    | (
        | 'Fashion'
        | 'Beauty'
        | 'Lifestyle'
        | 'Food & Beverage'
        | 'Tech'
        | 'Finance'
        | 'Gaming'
        | 'Travel'
        | 'Health & Wellness'
        | 'Entertainment'
        | 'Automobile'
        | 'Real Estate'
        | 'Education'
        | 'D2C / E-commerce'
      )[]
    | null;
  website?: string | null;
  description?: string | null;
  isProfileComplete?: boolean | null;
  completedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Edit influencer onboarding options. Keep value as the JSON object used by the app.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "onboarding-settings".
 */
export interface OnboardingSetting {
  id: string;
  key: string;
  /**
   * Expected keys: cities, platforms, primaryPlatforms, secondaryPlatforms, contentCategories, contentLanguages, collaborationPreferences, collaborationPreferenceOptions, validation.
   */
  value:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'cms-users';
        value: string | CmsUser;
      } | null)
    | ({
        relationTo: 'app-users';
        value: string | AppUser;
      } | null)
    | ({
        relationTo: 'agency-profiles';
        value: string | AgencyProfile;
      } | null)
    | ({
        relationTo: 'influencer-profiles';
        value: string | InfluencerProfile;
      } | null)
    | ({
        relationTo: 'onboarding-settings';
        value: string | OnboardingSetting;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'cms-users';
    value: string | CmsUser;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'cms-users';
    value: string | CmsUser;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cms-users_select".
 */
export interface CmsUsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app-users_select".
 */
export interface AppUsersSelect<T extends boolean = true> {
  mobile?: T;
  role?: T;
  isMobileVerified?: T;
  lastOtpRequestedAt?: T;
  lastLoginAt?: T;
  influencerProfile?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agency-profiles_select".
 */
export interface AgencyProfilesSelect<T extends boolean = true> {
  userId?: T;
  mobile?: T;
  agencyName?: T;
  contactPerson?: T;
  city?: T;
  agencyType?: T;
  teamSize?: T;
  creatorsManaged?: T;
  focusAreas?: T;
  website?: T;
  description?: T;
  isProfileComplete?: T;
  completedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "influencer-profiles_select".
 */
export interface InfluencerProfilesSelect<T extends boolean = true> {
  name?: T;
  city?: T;
  userId?: T;
  mobile?: T;
  platforms?:
    | T
    | {
        platform?: T;
        username?: T;
        channelName?: T;
        followers?: T;
        subscribers?: T;
        engagement?: T;
        id?: T;
      };
  contentCategories?: T;
  contentLanguages?: T;
  bio?: T;
  collaborationPreference?: T;
  rateRange?:
    | T
    | {
        min?: T;
        max?: T;
        currency?: T;
      };
  pastCollaborations?: T;
  portfolioLink?: T;
  isProfileComplete?: T;
  completedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "onboarding-settings_select".
 */
export interface OnboardingSettingsSelect<T extends boolean = true> {
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}